name: mgnify-lr
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - python
  - pip
  - matplotlib
  - minimap2
  - samtools
  - racon
  - medaka
  - flye
  - prodigal
  - diamond
  - fastp
  - pilon
  - bwa-mem2
  - spades
  - nodejs
  - pip:
    - toil
    - cwltool
    - packaging
    
