name: mgnify-lr
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - minimap2
  - samtools
  - racon
  - medaka
  - flye
  - prodigal
  - diamond
  - fastp
  - matplotlib
  - pilon
  - bwa-mem2
  - spades
