# Dokerfile for Medaka

FROM ubuntu:latest AS builder

ARG medakaVer=1.2.3

# install dependencies
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        python3 \
        python3-pip \
        python3-venv 

RUN python3 -m venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

# install tensorflow and medaka
RUN pip3 install medaka==${medakaVer}

# Target container
FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive
RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        python3-minimal \
        python3-distutils \
        samtools \
        tabix \
        bcftools \
        minimap2 && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY --from=builder /opt/venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

LABEL software="Medaka"
LABEL software.version="1.2.3"
LABEL description="Medaka is a tool to create consensus sequences and variant calls from nanopore sequencing data."
LABEL website="https://github.com/nanoporetech/medaka"
LABEL license="https://github.com/nanoporetech/medaka/blob/master/LICENSE.md"

# for singularity compatibility
ENV LC_ALL=C

RUN mkdir /data
WORKDIR /data

CMD ["/bin/bash" "-c"]