# Dokerfile for Medaka

FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive
RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        python3 \
        python3-pip \
        samtools \
        tabix \
        bcftools \
        minimap2 && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install --upgrade pip && \
    pip3 install tensorflow==2.2.0 && \
    pip3 install medaka==1.1.3

LABEL software="Medaka"
LABEL software.version="1.1.3"
LABEL description="Medaka is a tool to create consensus sequences and variant calls from nanopore sequencing data."
LABEL website="https://github.com/nanoporetech/medaka"
LABEL license="https://github.com/nanoporetech/medaka/blob/master/LICENSE.md"

# for singularity compatibility
ENV LC_ALL=C

RUN mkdir /data
WORKDIR /data

CMD ["/bin/bash" "-c"]