# Dokerfile for Medaka

FROM conda/miniconda3:latest

ENV DEBIAN_FRONTEND noninteractive

RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda install medaka && \
    conda clean -a

LABEL software="Medaka"
LABEL software.version="1.1.3"
LABEL description="Medaka is a tool to create consensus sequences and variant calls from nanopore sequencing data."
LABEL website="https://github.com/nanoporetech/medaka"
LABEL license="https://github.com/nanoporetech/medaka/blob/master/LICENSE.md"

# for singularity compatibility
ENV LC_ALL=C

RUN mkdir /data
WORKDIR /data

CMD ["/bin/bash" "-c"]